version: '3.8'
services:
  # Cypress container
  cypress:
    environment:
      - CLIENT_ENDPOINT=http://bond-sdk-cards-client:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}
      - CYPRESS_CREDIT_CARD_ID=${CYPRESS_CREDIT_CARD_ID}
      - CYPRESS_CREDIT_CARD_NUMBER=${CYPRESS_CREDIT_CARD_NUMBER}
      - CYPRESS_CREDIT_CARD_EXP=${CYPRESS_CREDIT_CARD_EXP}
      - CYPRESS_CREDIT_CARD_CVV=${CYPRESS_CREDIT_CARD_CVV}
      - CYPRESS_CREDIT_CARD_PIN=${CYPRESS_CREDIT_CARD_PIN}
      - CYPRESS_CREDIT_CARD_NEW_PIN=${CYPRESS_CREDIT_CARD_NEW_PIN}
      - CYPRESS_DEBIT_CARD_ID=${CYPRESS_DEBIT_CARD_ID}
      - CYPRESS_DEBIT_CARD_NUMBER=${CYPRESS_DEBIT_CARD_NUMBER}
      - CYPRESS_DEBIT_CARD_EXP=${CYPRESS_DEBIT_CARD_EXP}
      - CYPRESS_DEBIT_CARD_CVV=${CYPRESS_DEBIT_CARD_CVV}
      - CYPRESS_DEBIT_CARD_PIN=${CYPRESS_DEBIT_CARD_PIN}
      - CYPRESS_DEBIT_CARD_NEW_PIN=${CYPRESS_DEBIT_CARD_NEW_PIN}
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}
      - COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}
      - COMMIT_INFO_AUTHOR=${COMMIT_INFO_AUTHOR}
      - COMMIT_INFO_SHA=${COMMIT_INFO_SHA}
      - COMMIT_INFO_REMOTE=${COMMIT_INFO_REMOTE}
      - CI_BID=${CI_BID}
    build:
      context: .
      dockerfile: cypress.Dockerfile
    container_name: cypress
    command: npx cypress run --headless --browser chrome --record --parallel --ci-build-id $CI_BID
    restart: unless-stopped
    extra_hosts:
      - 'bond-sdk-cards-client:${SDK_CONTAINER_IP}'
