version: '3.8'
services:
  # Cypress container
  cypress:
    environment:
      - CLIENT_ENDPOINT=http://bond-sdk-cards-client:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}
      - CYPRESS_CREDIT_CARD_ID=${CYPRESS_CREDIT_CARD_ID}
      - CYPRESS_CREDIT_CARD_NUMBER=${CYPRESS_CREDIT_CARD_NUMBER}
      - CYPRESS_CREDIT_CARD_EXP=${CYPRESS_CREDIT_CARD_EXP}
      - CYPRESS_CREDIT_CARD_CVV=${CYPRESS_CREDIT_CARD_CVV}
      - CYPRESS_CREDIT_CARD_PIN=${CYPRESS_CREDIT_CARD_PIN}
      - CYPRESS_CREDIT_CARD_NEW_PIN=${CYPRESS_CREDIT_CARD_NEW_PIN}
      - CYPRESS_DEBIT_CARD_ID=${CYPRESS_DEBIT_CARD_ID}
      - CYPRESS_DEBIT_CARD_NUMBER=${CYPRESS_DEBIT_CARD_NUMBER}
      - CYPRESS_DEBIT_CARD_EXP=${CYPRESS_DEBIT_CARD_EXP}
      - CYPRESS_DEBIT_CARD_CVV=${CYPRESS_DEBIT_CARD_CVV}
      - CYPRESS_DEBIT_CARD_PIN=${CYPRESS_DEBIT_CARD_PIN}
      - CYPRESS_DEBIT_CARD_NEW_PIN=${CYPRESS_DEBIT_CARD_NEW_PIN}
    build:
      context: .
      dockerfile: cypress.Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    container_name: cypress
    restart: unless-stopped
    extra_hosts:
      - 'bond-sdk-cards-client:${SDK_CONTAINER_IP}'
