version: '3.8'
services:
  client:
    environment:
      - CLIENT_ENDPOINT=http://localhost:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}

    build:
      context: .
      dockerfile: Dockerfile
    container_name: bond-sdk-cards-client
    restart: unless-stopped
    ports:
      - 8080:8080
