version: '3.8'
services:
  client:
    environment:
      - CLIENT_ENDPOINT=http://localhost:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}

    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    container_name: bond-sdk-cards-client
    restart: unless-stopped
    ports:
      - 8080:8080
