version: 2.1

parameters:
  sdk_image:
    type: string
    default: ${CIRCLE_WORKFLOW_ID}

#Orb importing
orbs:
  artifactory-orb: jfrog/artifactory-orb@1.0.1 #Build and push to Artifactory
  aws-cli: circleci/aws-cli@1.4.0
  cypress: cypress-io/cypress@1.28.0

jobs:

  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: dist
          paths:
            - ?*

  publish_local_registry:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build and publish to local registry
          command: |
            docker run -d -p 5000:5000 --restart=always --name registry registry:2
            docker build --build-arg NODE_ENV=NODE_ENV -t localhost:5000/bond-sdk-cards:${CIRCLE_WORKFLOW_ID} .
            docker push localhost:5000/bond-sdk-cards:${CIRCLE_WORKFLOW_ID}
            mkdir -p saved_images
            docker save -o saved_images/docker_image_sdk.tar localhost:5000/bond-sdk-cards:${CIRCLE_WORKFLOW_ID}
      - persist_to_workspace:
          root: saved_images
          paths:
            - docker_image_sdk.tar

  cypress:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: saved_images
      - artifactory-orb/install
      - artifactory-orb/configure
      - artifactory-orb/docker-login:
          docker-registry: ${ARTIFACTORY_REGISTRY}
      - run:
          name: Start containers
          command: |
            docker load -i saved_images/docker_image_sdk.tar
            export SDK_IMAGE=<< pipeline.parameters.sdk_image >>
            docker-compose -f docker-compose-test.yaml up -d
            sleep 30
      - run:
          name: Perform e2e Cypress Tests
          command: |
            SDK_CONTAINER_ID=$(docker ps -aqf "name=bond-sdk-cards-client")
            SDK_CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $SDK_CONTAINER_ID)
            export SDK_CONTAINER_IP=${SDK_CONTAINER_IP}
            docker-compose -f docker-compose-cypress.yaml config
            docker-compose -f docker-compose-cypress.yaml up --timeout 600 --exit-code-from cypress
          no_output_timeout: 6m

  push_to_cdn:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          profile-name: default
      - run: 
          name: push
          command: |
            FULL_VERSION=$( sed -En 's/[ ]*"version"[ ]*:[ ]*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/p' package.json )
            MAJOR_VERSION=$( echo ${FULL_VERSION} | cut -d'.' -f1 )
            MINOR_VERSION=$( echo ${FULL_VERSION} | cut -d'.' -f2 )
            PATCH_VERSION=$( echo ${FULL_VERSION} | cut -d'.' -f3 )
            aws s3 cp dist/bond-sdk-cards.js s3://bond-prod-web-assets/sdk/cards/archive/v${FULL_VERSION}-${CIRCLE_BRANCH}-${CIRCLE_SHA1}.js
            if [[ ${CIRCLE_BRANCH} =~ ^main$ ]] ; then
              aws s3 cp dist/bond-sdk-cards.js s3://bond-prod-web-assets/sdk/cards/v${MAJOR_VERSION}/bond-sdk-cards.js
              aws s3 cp dist/bond-sdk-cards.js s3://bond-prod-web-assets/sdk/cards/v/${MAJOR_VERSION}/${MINOR_VERSION}/${PATCH_VERSION}/bond-sdk-cards.js
            fi

workflows:

  version: 2

  pipeline:
    jobs:
      - build
      # - build:
      #     requires:
      #       - cypress
      # - publish_local_registry
      # - cypress:
      #     requires:
      #       - publish_local_registry
      # - push_to_cdn:
      #     requires: 
      #       - build
